backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages"
    create: true
    files:
      - label: "Site content"
        create: true
        slug: "{{ title }}"
        name: "page"
        file: "content"
        fields:
          - {
              label: Content Title,
              name: title,
              widget: string,
              allow_add: true,
            }
          - {
              label: Content Body,
              name: body,
              widget: markdown,
              allow_add: true,
            }
          - { label: Image, name: image, widget: image, allow_add: true }
