backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages"
    files: 
      - label: "Home Page"
      name: "homePage"
      file: "content/home.md"
        fields:
          - { label: "Content Title", name: "title", widget: "string" }
          - { label: "Content Body", name: "body", widget: "markdown", option: { linkAttrs: target: _blank, rel: noreferrer noopener } }
