backend:
  name: github
  repo: adventure-capitalist/ashleys-animals
  branch: master
  auth_endpoint: auth
  base_url: https://modest-noether-9da66c.netlify.com/

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages"
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/home.md"
        fields:
          - { label: Content Title, name: title, widget: string }
          - { label: Content Body, name: body, widget: markdown }
          - { label: Image, name: image, widget: image }
