backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages"
    folder: "src/pages"
    files: [index.js]
    fields:
      - { label: "Content Title", name: "title", widget: "string" }
      - {
          label: "Content Body",
          name: "body",
          widget: "markdown",
          option: { linkAttrs: { target: _blank, rel: noreferrer noopener } },
        }
